---
ID: "3952851e-6bfb-4e8c-8ee3-af676c228416"
Parent: "0baeb29c-a8ff-4031-8a7d-420a186af3c2"
Template: "0baeb29c-a8ff-4031-8a7d-420a186af3c2"
Path: /sitecore/templates/Car/Folder Template/Author Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {2E7CB92B-8A6A-468E-BB55-B8AEA2701EC5}
    {66D9DE4A-4FA1-42C8-99EC-4FC2C48D5EF0}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190511T052317Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
