---
ID: "5d582676-42e8-4752-8a2a-a2a21f7aea80"
Parent: "587d6490-e677-4889-aa77-f3db678e0831"
Template: "587d6490-e677-4889-aa77-f3db678e0831"
Path: /sitecore/templates/Car/Page Template/Author/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 0
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{13140D95-8D2D-4035-9FDA-42111E13EE25}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190511T051903Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "a1534ae8-1754-4c8f-b57b-476254571f5e"
      Hint: First Name
      Value: $name
