---
ID: "1d9707c6-0397-4835-99d9-39f0e7e0ff6d"
Parent: "c5b8ba62-f752-4ac0-826f-f3332ad5a672"
Template: "c5b8ba62-f752-4ac0-826f-f3332ad5a672"
Path: /sitecore/templates/Car/Parameter Template/No of Slides/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230522T064220Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
